### ISSUE TITLE
lecoal.exe error

### ISSUE THREAD

**Issue by LilimVipera** [AYasinAkalin/MELE_quickIniEditor#14]
Hi!
Sorry, if I may just being stupid but I'm somehow trying to work myself into this topic

I tried getting the contents of Coalesced_INT.bin, cause I wanted to change smth but didn't know the exact phrasing and so wanted to use lecoal.exe
But when using the PowerShell, I get the following error:
'.\LECoal.exe unpack Coalesced_INT.bin D:\MELE\ME1_Coalesced
Error in command interpretation:
Expected the 'from' argument for 'unpack' to be an existing file

    at LECoal.CoalescedTool..ctor(String[] args)
    at LECoal.Program.Main(String[] args)

Run the tool with '?' or '--help' argument for usage reference.'

The exact string was `.\LECoal.exe unpack Coalesced_INT.bin D:\MELE\ME1_Coalesced` (like in the help described as it was fitting)

Btw I used it from the lecoal-directory, so that's not the issue

And I know, I could wait for seasoned modders who change exactly what I want, but I want to tweak the game to my liking. Ini-files are easy, I started playing with them when TSE:IV was quite new ;)

**Comment by AYasinAkalin** [comment]
I'll try to help, but this is not an issue with my tool.

First I'm sorry that you found the syntax confusing. I'll try to explain it at the end.

Now let's try to use LECoal. From what you wrote 

> `Expected the 'from' argument for 'unpack' to be an existing file`

I understood that LECoal.exe couldn't find `Coalesced_INT.bin` file you are trying to extract. Possible reason is that that file is not in the same folder as LECoal.exe. `Coalesced_INT.bin` **doesn't have to be** in the same folder as LECoal.exe but your command instructs LECoal like it is. So it looks there (where LECoal.exe is), couldn't find it, give you the error.

**Possible solutions**:

1. Copy `Coalesced_INT.bin` where `LECoal.exe` is and use this command instead

```.\LECoal.exe unpack .\Coalesced_INT.bin D:\MELE\ME1_Coalesced```

2. Change your command so that `LECoal.exe` finds your files. As you might understand your command (or any command for LECoal.exe) consists of 4 parts.
  - **Path of the program**. On this instance you are running `LECoal.exe` in the folder opened in Command Prompt or Powershell. `.\` part tells Command Prompt to look for the folder it is operating in.
  - **Instruction **: This is either `unpack` or `repack` as developer of LECoal made it so.
  - **`from` argument**: Tells `LECoal.exe` where `Coalesced_INT.bin` is
  - **`to` argument**: Tells `LECoal.exe` where to export all the extracted files.
  
You only need to change **`from` argument**. Just drag-and-drop your `Coalesced_INT.bin` on to Command Prompt or Powershell once you write `.\LECoal.exe unpack `. After drag-and-drop, put `D:\MELE\ME1_Coalesced` or whatever folder you want files to be extracted. You can also drag-and-drop this folder too. And run the command.

**Comment by AYasinAkalin** [comment]
You can also use my tool to extract `Coalesced_INT.bin` with a quick tweak.

Right click on `cli.bat`, click on edit. Or just open it with a text editor.
Just above this line `:: SAVE COPIED FILES AS BACKUP QUIETLY` at line number 67 put the following three lines, save and exit.
```
ECHO Extracted! Press any key to exit...
pause >nul
EXIT 1
```

Now when you run my tool it will extract `Coalesced_INT.bin` and stop. Extracted files will be created at `Temp\unpacked_coalescend` folder.

**Comment by AYasinAkalin** [comment]
Marking the issue as wontfix as this is not in the scope of this tool. 

@LilimVipera Let me know if you get it to work.

**Comment by LilimVipera** [comment]
Ah, okay, thank you very much! It worked well :)
In retrospect it was so simple, it's embarrassing...
But to defend my last bit of honor: I'm new to this ^^'

**Comment by AYasinAkalin** [comment]
### Guilty as charged! Off with his head! Fetch the guillotine.
